# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot = {

    extraModulePackages = [ ];
    kernelModules = [ "kvm-intel" ];
    initrd = {

      availableKernelModules =
        [ "xhci_pci" "ahci" "nvme" "usbhid" "rtsx_pci_sdmmc" ];
      kernelModules = [ "dm-snapshot" "dm-crypt" ];
      luks.devices = {
        cryptlvm = {
          device = "/dev/disk/by-uuid/127612b2-cb06-4088-b281-bb82da4ff499";
          preLVM = false;
        };
      };
    };
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/c026510a-842a-46fe-b5fa-79af176c501b";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/85DC-082F";
    fsType = "vfat";
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/bc5c023a-25f2-4b28-8fbe-a4dd75f15489"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
